version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/student_management_app
    ports:
      - 8000:8000
    image: app:student_management_app1
    container_name: new_django_container
    command: python manage.py runserver 0.0.0.0:8000

